@startuml

state Initializing #palegreen {
}
state Checking #palegreen {
}
state Releasing #palegreen {
}

[*] --> NotInitialized: Create
NotInitialized --> Initializing: Initialize
Initializing --> InitializedAvailable: Value
Initializing --> Initializing: Retry
InitializedAvailable --> PreCheck: Checkout 
PreCheck --> Checking: Check
Checking --> Disposing: Dispose
Checking --> CheckedOut: Checkout
InitializedAvailable --> Releasing: IdleTimeout
Releasing --> Disposing: Dispose 
Disposing --> NotInitialized: Disposed
CheckedOut --> InitializedAvailable: Checkin
PreCheck --> CheckedOut: Checkout

Initializing: if initialize fails
Initializing: send Retry to self with delay
Initializing: else 
Initializing: send Value to self

PreCheck: if checked recently
PreCheck: send Checkout to self
PreCheck: else 
PreCheck: send Check to self

Checking: if health check passes
Checking: send Checkout to self
Checking: else
Checking: send Dispose to self

note bottom of CheckedOut
  the Member is pushed to the 
  next pool subscriber for active 
  use
end note

@enduml

