@startuml

state Initializing #palegreen {
}
state Checking #palegreen {
}
state Releasing #palegreen {
}

[*] --> NotInitialized: Create
NotInitialized --> Initializing: Initialize
Initializing --> InitializedAvailable: Value
Initializing --> Initializing: Retry
InitializedAvailable --> Checking: Checkout
Checking --> Disposing: Dispose
Checking --> CheckedOut: Ok
InitializedAvailable --> Releasing: IdleTimeout
Releasing --> Disposing: Dispose 
Disposing --> NotInitialized: Disposed
CheckedOut --> InitializedAvailable: Checkin

note bottom of CheckedOut
  the Member is pushed to the 
  next pool subscriber for active 
  use
end note

@enduml

